#! /bin/bash

usage="Usage : $0 [commit \"Message pour le commit\" | pull]"
if [ $# -ge 1 ]
then
	if [ -d "`pwd`/.git" ]
	then
		if [ $1 = "init" ]
		then
			cp ./GIT ~/local/bin/
			chmod u+x ~/local/bin/GIT
		else
			if [ $1 = "commit" ]
			then
				if [ $# -lt 2 ]
				then
					echo "$usage"
				else
					git add *
					git rm data/img/*_* --cached
					git commit -m "$1"
					git push origin master
				fi
			else
				if [ $1 = "pull" ]
				then
					git pull origin master
					if [ -f perm.sh ]
					then
						bash perm.sh
					fi
				else
					echo "$usage"
				fi
			fi
		fi
	else
		echo "No git repository initialized for this directory ..."
	fi
else
	echo "$usage"
fi
